### ISSUE TITLE
Network + Offline Storage Example

### ISSUE THREAD

**Issue by Abdul-Moiz** [sergdort/CleanArchitectureRxSwift#10]
Can you add an example for offline storage? 
Like fetching data from the network then storing locally and displaying into the UI.

**Comment by sergdort** [comment]
Yeah, good idea! 👍 

Will try to find some time :)

**Comment by sergdort** [comment]
Hi, @Abdul-Moiz I've added example here #12 feel free to open a discussion about implementation or anybody who is interested :)
