### ISSUE TITLE
Please provide a license for your code

### ISSUE THREAD

**Issue by mrtj** [sergdort/CleanArchitectureRxSwift#14]
Hi sergdort, thanks for the excellent work! Apart from the nice concept of the architecture, I found some great ideas in some utility classes (ErrorTracker, ActivityIndicator, etc.) and would like to know if and how I can use them but I did not find any license info attached to your project. Could you provide it please?

**Comment by sergdort** [comment]
Hi, @mrtj . I've added MIT licence to the project. Feel free to use anything you want :)
