### ISSUE TITLE
Pull to refresh and Pagination loading support.

### ISSUE THREAD

**Issue by khoren93** [sergdort/CleanArchitectureRxSwift#21]
Hi, Thanks for really good architecture template :)
Have you a plan to add Pull to Refresh and Infinite Scrolling features?
It's will be good for networking part.
Thanks again.

**Comment by sergdort** [comment]
Hi, @khoren93 
I feel like what you are asking is a bit different from the purpose of this repo. Its goal is to show how we can build apps driven by domain problems in a clean way abrasing SOLID principles.

There are plenty of examples around the web regarding problems you are asking. There is also example of paginated list in the [RxFeedback](https://github.com/kzaher/RxFeedback) repo
