### ISSUE TITLE
Providing services to another flows

### ISSUE THREAD

**Issue by DocMacFain** [sergdort/CleanArchitectureRxSwift#24]
Hello, thank you for great sample "how to explore CleanArch with RX using swift"!

I have few questions, I would be thankful for clarification.

0) If I have few flows, likes authentication and home (an example: tab bar with slide menu, where a lot use cases). Should I group use cases like authenticationUseCases which consist of AuthenticationServiceLocator which provide cases just for this flow and so on for other flows?

1) If answer for first question is yes, so how can I provide services to other flows? I mean, when I start application, I can configure welcome scene (as at your example), where I have authentication flow with authenticationService. After it I should redirect user to another flow, with another useCases (something like HomeServiceLocator). Where should I initialize HomeScene with HomeServiceLocator?

**Comment by sergdort** [comment]
Hi, @dotprox 

The way we do it is that we have `Dependencies` which contains "lower level" abstractions, e.g `Network` and we have an `Assembly` per flow which knows how to build a module. So `Dependencies` are responsible for creating Assembly injecting required stuff  and `Assembly` creates a `ViewModel` with injected `UseCase`s

**Comment by sergdort** [comment]
Feel free to reopen if you have any questions
