### ISSUE TITLE
ViewModel and UIKit

### ISSUE THREAD

**Issue by IvanKalaica** [sergdort/CleanArchitectureRxSwift#39]
Should [viewModel](https://github.com/sergdort/CleanArchitectureRxSwift/blob/55c852bbd7b4e5f9ee30426e2acdb7b038e848be/CleanArchitectureRxSwift/Scenes/CreatePost/CreatePostViewModel.swift#L9) import framework that exposes UIKit like RxCocoa? Maybe it's better to expose input/output as Observable's and convert them to Driver in viewController implementation where it's legit to import RxCocoa?

**Comment by sergdort** [comment]
Hi, @IvanKalaica! Yeah, I've heard quite a lot people saying that `ViewModel` should be platform agnostic e.g in case you would want to make a MacOS app, but IMHO this is not possible ¯\_(ツ)_/¯

And regarding `Input/Output` approach, at the moment I'm not sure if it's visible solution in more complex examples. We recently started to use [RxFeedback](https://github.com/NoTests/RxFeedback.swift) in our app and we are very happy =)

**Comment by IvanKalaica** [comment]
Yeah, I also use RxFeedback also in my projects inside ViewModel with input/output as Observables. Currently this doesn't make sense since RxFeedback imports RxCocoa. It would be good if I can import just a Observable RxFeedback. Then it's possible to have platform agnostic ViewModel.

**Comment by sergdort** [comment]
How do you work with `UIImage` for example?

**Comment by IvanKalaica** [comment]
I would expose `var imageData: Observable<Data?>`in ViewModel and convert it on async scheduler to format I need (UIImage) where I need it (cell or viewController).

**Comment by sergdort** [comment]
IMHO it violates original design idea ¯\_(ツ)_/¯

>  The view model then provides data from the model in a form that the view can easily use.

from [here](https://msdn.microsoft.com/en-us/library/hh848246.aspx)

**Comment by IvanKalaica** [comment]
Yeah, I know and I agree. :)

I think UIImage is only data type for which I had to make such transformation outside ViewModel.

IMHO it's small price to pay considering the benefits.

**Comment by IvanKalaica** [comment]
and UIFont, UIColor... I think the price raises as time passes. :)
