### ISSUE TITLE
OfflineFirst principle using CleanArchitectureRxSwift

### ISSUE THREAD

**Issue by neutrum** [sergdort/CleanArchitectureRxSwift#45]
It's more of a question then Issue. But how would you implement OfflineFirst principle and keep for example both platforms intact and still let them be modular (networking, realm i.e). I suppose I should create another platform or layer below the domain and in the UseCase I could use both the NetworkingPlatform and RealmPlatform and just merge the results. Or is there some other way how to do it?

**Comment by sergdort** [comment]
Hi @neutrum! Please see https://github.com/sergdort/CleanArchitectureRxSwift/issues/30 for more details
