### ISSUE TITLE
Realm Object has no member 'build'

### ISSUE THREAD

**Issue by ghost** [sergdort/CleanArchitectureRxSwift#46]
Type 'RMProduct' has no member 'build'

```
extension Product: RealmRepresentable {
    func asRealm() -> RMProduct {
        return RMProduct.build{ object in
            object.name = name
        }
    }
}
```

Can someone help to understand what is wrong ?

**Comment by sergdort** [comment]
Hi, @HaythemBenAicha `build` is an extension method realm does not have it :) Please see [implementation](https://github.com/sergdort/CleanArchitectureRxSwift/blob/master/RealmPlatform/Utility/Extensions/Realm%2BExt.swift#L6) for more details

**Comment by sergdort** [comment]
Seems to be resolved ¯\_(ツ)_/¯
