### ISSUE TITLE
how creat framwork

### ISSUE THREAD

**Issue by kavoskhajavi** [sergdort/CleanArchitectureRxSwift#47]
how creat framwork in swift 4 like sample

**Comment by sergdort** [comment]
Hope this helps 

<img width="615" alt="screen shot 2018-06-29 at 09 59 41" src="https://user-images.githubusercontent.com/4622322/42083698-8e687fe6-7b83-11e8-9bc4-e7ba84b8a18e.png">

<img width="717" alt="screen shot 2018-06-29 at 09 54 48" src="https://user-images.githubusercontent.com/4622322/42083710-93952d02-7b83-11e8-9967-9985e8af61ab.png">

**Comment by sergdort** [comment]
Feel free to reopen if you have any questions
