### ISSUE TITLE
xCode 8.3 failed to build

### ISSUE THREAD

**Issue by AYastrebov** [sergdort/CleanArchitectureRxSwift#5]
After updating to xCode 8.3, the project fails to build. I couldn't figure out why

![2017-03-27_23-42-41](https://cloud.githubusercontent.com/assets/739037/24377208/381e8414-1347-11e7-94ff-61795810ff7a.png)

**Comment by AYastrebov** [comment]
Seems like a [realm issue](https://github.com/realm/realm-cocoa/issues/4784)

**Comment by sergdort** [comment]
Yeah, seem like 
Because the problem is [here](https://github.com/sergdort/CleanArchitectureRxSwift/blob/master/RealmPlatform/Repository/Repository.swift#L62)

**Comment by AYastrebov** [comment]
wow, nice catch @sergdort
