### ISSUE TITLE
Protocol conformance

### ISSUE THREAD

**Issue by fodderkonoko** [sergdort/CleanArchitectureRxSwift#50]
`final class Repository<T: CoreDataRepresentable>: AbstractRepository where T == T.CoreDataType.DomainType `

could not understand how **T.CoreDataType.DomainType** is returning back the Domain Type .
 
In case of **Domain.Post**, **Post** is conforming to **CoreDataRepresentable**
`extension Post: CoreDataRepresentable {
    typealias CoreDataType = CDPost
 ....

}`

and CDPost conforms to **DomainConvertibleType** and **Persistable**
But nowhere `associatedtype DomainType` is defined.

Can you please clarify?

**Comment by sergdort** [comment]
Hi, @fodderkonoko 

There are three protocols involved:

```swift
protocol DomainConvertibleType {
    associatedtype DomainType

    func asDomain() -> DomainType
}

protocol CoreDataRepresentable {
    associatedtype CoreDataType: Persistable
    
    var uid: String {get}
    
    func update(entity: CoreDataType)
}

protocol Persistable: NSFetchRequestResult, DomainConvertibleType {
    static var entityName: String {get}
    static func fetchRequest() -> NSFetchRequest<Self>
}
```

The signature of `Repository` is 

```swift
final class Repository<T: CoreDataRepresentable>: AbstractRepository where T == T.CoreDataType.DomainType { 
}

// This is how we "bind" two types together 
extension CDPost: DomainConvertibleType {}
extension Post: CoreDataRepresentable {}
```
So `where` statement essentially saying `T` should be `CoreDataRepresentable` e.g `Post` which should have corresponding core data type `CDPost` which should be `DomainConvertibleType`. This allows us to ensure that all `CoreDataRepresentable` types has corresponding core data types that can be mapped back to `Domain` type. May be this can be improved somehow, but I wasn't able to come up with something better ¯\_(ツ)_/¯

Hope this make sense :)

**Comment by fodderkonoko** [comment]
thanks for the response. definitely it makes sense.
but i am confused on how `associatedtype Domaintype` is typecasted to **Post** when **CDPost** confirms to **DomainConvertibleType**. you have not used typealias for this anywhere in the codebase.
sorry for bugging you but it's something i really need to understand

**Comment by sergdort** [comment]
It’s not mandatory to add typealias, afaik compiler can figure out associate type from the method signature of the conforming type

**Comment by fodderkonoko** [comment]
thank you very much for the explanation.

i was guessing that but not sure.
