### ISSUE TITLE
Moya

### ISSUE THREAD

**Issue by Kamajabu** [sergdort/CleanArchitectureRxSwift#7]
Hey, 

Have you thought about refactoring code by using [Moya](https://github.com/Moya/Moya)? Rx + Alamofire + ObjectMapper IMO asks for it :) 

Great example btw, very clean and helpful one :)

**Comment by sergdort** [comment]
Hi, @Kamajabu, thanks!
To be honest have never tried Moya :) But heard a lot of good things about it
The idea of examples is to show prove of concept rather then use case of particular library :)

**Comment by sergdort** [comment]
I think we can close this one :)

**Comment by ttuygun** [comment]
Hello @Kamajabu. I already implemented with this architecture with Moya. https://github.com/ttuygun/moviedb-ios
I would appreciate if you can feedback.
