### ISSUE TITLE
Multiple models for Repository in single UseCase.

### ISSUE THREAD

**Issue by kaungsoe** [sergdort/CleanArchitectureRxSwift#78]
Let's say we want to save PostDetail model also in this PostsUseCase, in that case, how do we satisfy the generic constraint for it. 

```
final class PostsUseCase<Repository>: Domain.PostsUseCase where Repository: AbstractRepository, Repository.T == Post {

    private let repository: Repository

    init(repository: Repository) {
        self.repository = repository
    }

     func save(postDetail: PostDetail) -> Observable<Void> {
        return repository.save(entity: postDetail)
    }

     func save(post: Post) -> Observable<Void> {
        return repository.save(entity: post)
    }

}
```

**Comment by sergdort** [comment]
I would make another UseCase. As it does handle a different part of the business logic 🤷‍♂️

**Comment by kaungsoe** [comment]
No workaround other than creating new usecase?

**Comment by sergdort** [comment]
I would not call it a workaround, but a good design practice. UseCases (and any classes in general) should be responsible for handling one peace of business logic, hence it will be easy to refactor, test and fix bugs.
